// Generated by CoffeeScript 1.6.2
(function() {
  var log, should;

  should = chai.should();

  log = function(msg) {
    return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
  };

  describe('Prezenter', function() {
    beforeEach(function() {
      return this.prez = new Prezenter();
    });
    return it('should have 8 items in data', function() {
      this.prez.data.length.should.equal(8);
      this.prez.init();
      return log(this.prez.currentElement);
    });
  });

}).call(this);
